# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dinosaur',
            new_name='Tweets',
        ),
        migrations.RenameField(
            model_name='tweets',
            old_name='species',
            new_name='text',
        ),
    ]
