# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20170424_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='favorites_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='media',
            field=models.URLField(default='asdf.org'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweet_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='user',
            field=models.TextField(default='bob'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='user_image',
            field=models.URLField(default='asdfa.org'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='user_url',
            field=models.URLField(default='asdf.org'),
            preserve_default=False,
        ),
    ]
