# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20170425_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='media',
        ),
    ]
